import PushNotificationIOS from '@react-native-community/push-notification-ios';
import PushNotification from 'react-native-push-notification';

export const setNotification = (date, title, content) => {
  console.log(date, 'date$$$$$$');
  let data = new Date(date);
  PushNotification.localNotificationSchedule({
    id: '123', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
    title: title, // (optional)
    message: content, // (required
    date: data,
    allowWhileIdle: false, // (optional) set notification to work while on doze, default: false
  });
};

export const cancelNotification = () => {
  PushNotification.cancelLocalNotification('123');
};
